{
  "mcpServers": {
    "neal-todos": {
      "type": "http",
      "url": "http://kewtie:3737/mcp/__TODO_MCP_TOKEN__"
    }
  },
  "permissions": {
    "allow": [
      "mcp__claude_ai_neal_todo__*",
      "WebSearch",
      "WebFetch",
      "Read",
      "Edit",
      "Write",
      "Bash(npm *)",
      "Bash(pnpm *)",
      "Bash(node *)",
      "Bash(uv *)",
      "Bash(brew list*)",
      "Bash(brew info*)",
      "Bash(brew search*)",
      "Bash(docker ps*)",
      "Bash(docker logs*)",
      "Bash(docker exec*)",
      "Bash(docker inspect*)",
      "Bash(docker build*)",
      "Bash(docker images*)",
      "Bash(docker history*)",
      "Bash(docker restart*)",
      "Bash(docker compose ps*)",
      "Bash(docker compose logs*)",
      "Bash(docker compose build*)",
      "Bash(docker compose restart*)",
      "Bash(docker compose up*)",
      "Bash(podman ps*)",
      "Bash(podman logs*)",
      "Bash(podman exec*)",
      "Bash(podman inspect*)",
      "Bash(podman build*)",
      "Bash(podman images*)",
      "Bash(podman history*)",
      "Bash(podman restart*)",
      "Bash(podman compose ps*)",
      "Bash(podman compose logs*)",
      "Bash(podman compose build*)",
      "Bash(podman compose restart*)",
      "Bash(podman compose up*)",
      "Bash(sqlite3 -readonly *)",
      "Bash(ls*)",
      "Bash(find *)",
      "Bash(grep *)",
      "Bash(cat *)",
      "Bash(echo *)",
      "Bash(pwd)",
      "Bash(which *)",
      "Bash(env)",
      "Bash(printenv *)",
      "Bash(curl *)",
      "Bash(python3 *)",
      "Bash(jq *)"
    ],
    "deny": [
      "Read(./.env)", "Edit(./.env)",
      "Read(./.env.*)", "Edit(./.env.*)",
      "Read(**/.env)", "Edit(**/.env)",
      "Read(**/.env.*)", "Edit(**/.env.*)",
      "Read(./.envrc)", "Edit(./.envrc)",
      "Read(**/.envrc)", "Edit(**/.envrc)",
      "Read(**/id_rsa)", "Edit(**/id_rsa)",
      "Read(**/id_ed25519)", "Edit(**/id_ed25519)",
      "Read(**/*.pem)", "Edit(**/*.pem)",
      "Read(**/*.key)", "Edit(**/*.key)",
      "Read(./.aws/credentials)", "Edit(./.aws/credentials)",
      "Read(**/.aws/credentials)", "Edit(**/.aws/credentials)",
      "Read(./.docker/config.json)", "Edit(./.docker/config.json)",
      "Read(**/.docker/config.json)", "Edit(**/.docker/config.json)",
      "Read(./.kube/config)", "Edit(./.kube/config)",
      "Read(**/.kube/config)", "Edit(**/.kube/config)",
      "Read(./.netrc)", "Edit(./.netrc)",
      "Read(**/.netrc)", "Edit(**/.netrc)",
      "Read(./.git-credentials)", "Edit(./.git-credentials)",
      "Read(**/.git-credentials)", "Edit(**/.git-credentials)",
      "Read(./.npmrc)", "Edit(./.npmrc)",
      "Read(**/.npmrc)", "Edit(**/.npmrc)",
      "Read(./.pypirc)", "Edit(./.pypirc)",
      "Read(**/.pypirc)", "Edit(**/.pypirc)",
      "Read(**/*.tfstate*)", "Edit(**/*.tfstate*)",
      "Read(./secrets.yaml)", "Edit(./secrets.yaml)",
      "Read(**/secrets.yaml)", "Edit(**/secrets.yaml)",
      "Read(./secrets.yml)", "Edit(./secrets.yml)",
      "Read(**/secrets.yml)", "Edit(**/secrets.yml)",
      "Read(./credentials.json)", "Edit(./credentials.json)",
      "Read(**/credentials.json)", "Edit(**/credentials.json)",
      "Bash(*.env*)",
      "Bash(*id_rsa*)",
      "Bash(*id_ed25519*)",
      "Bash(*.pem*)",
      "Bash(*.key*)",
      "Bash(*.aws/credentials*)",
      "Bash(*.docker/config.json*)",
      "Bash(*.kube/config*)",
      "Bash(*.netrc*)",
      "Bash(*.git-credentials*)",
      "Bash(*.npmrc*)",
      "Bash(*.pypirc*)",
      "Bash(*.tfstate*)",
      "Bash(*secrets.yaml*)",
      "Bash(*secrets.yml*)",
      "Bash(*credentials.json*)",
      "Bash(rm -rf *)",
      "Bash(sudo rm *)",
      "Bash(git push --force*)",
      "Bash(git reset --hard*)",
      "Bash(git clean -f*)",
      "Bash(chmod -R 777 *)"
    ]
  },
  "defaultMode": "plan",
  "includeCoAuthoredBy": false
}
