{
  "mcpServers": {
    "neal-todos": {
      "type": "http",
      "url": "http://kewtie:3737/mcp/__TODO_MCP_TOKEN__"
    }
  },
  "permissions": {
    "allow": [
      "mcp__claude_ai_neal_todo__*",
      "WebSearch",
      "WebFetch",
      "Read",
      "Edit",
      "Write",
      "Bash(npm *)",
      "Bash(pnpm *)",
      "Bash(node *)",
      "Bash(uv *)",
      "Bash(brew list*)",
      "Bash(brew info*)",
      "Bash(brew search*)",
      "Bash(docker ps*)",
      "Bash(docker logs*)",
      "Bash(docker exec*)",
      "Bash(docker inspect*)",
      "Bash(docker build*)",
      "Bash(docker images*)",
      "Bash(docker history*)",
      "Bash(docker restart*)",
      "Bash(docker compose ps*)",
      "Bash(docker compose logs*)",
      "Bash(docker compose build*)",
      "Bash(docker compose restart*)",
      "Bash(docker compose up*)",
      "Bash(podman ps*)",
      "Bash(podman logs*)",
      "Bash(podman exec*)",
      "Bash(podman inspect*)",
      "Bash(podman build*)",
      "Bash(podman images*)",
      "Bash(podman history*)",
      "Bash(podman restart*)",
      "Bash(podman compose ps*)",
      "Bash(podman compose logs*)",
      "Bash(podman compose build*)",
      "Bash(podman compose restart*)",
      "Bash(podman compose up*)",
      "Bash(sqlite3 -readonly *)",
      "Bash(ls*)",
      "Bash(find *)",
      "Bash(grep *)",
      "Bash(cat *)",
      "Bash(echo *)",
      "Bash(pwd)",
      "Bash(which *)",
      "Bash(env)",
      "Bash(printenv *)",
      "Bash(curl *)",
      "Bash(python3 *)",
      "Bash(jq *)"
    ],
    "deny": [
      "Read(./.env)", "Edit(./.env)",
      "Read(**/.env)", "Edit(**/.env)",
      "Read(./.env.local)", "Edit(./.env.local)",
      "Read(**/.env.local)", "Edit(**/.env.local)",
      "Read(./.env.development)", "Edit(./.env.development)",
      "Read(**/.env.development)", "Edit(**/.env.development)",
      "Read(./.env.development.local)", "Edit(./.env.development.local)",
      "Read(**/.env.development.local)", "Edit(**/.env.development.local)",
      "Read(./.env.dev)", "Edit(./.env.dev)",
      "Read(**/.env.dev)", "Edit(**/.env.dev)",
      "Read(./.env.dev.local)", "Edit(./.env.dev.local)",
      "Read(**/.env.dev.local)", "Edit(**/.env.dev.local)",
      "Read(./.env.production)", "Edit(./.env.production)",
      "Read(**/.env.production)", "Edit(**/.env.production)",
      "Read(./.env.production.local)", "Edit(./.env.production.local)",
      "Read(**/.env.production.local)", "Edit(**/.env.production.local)",
      "Read(./.env.prod)", "Edit(./.env.prod)",
      "Read(**/.env.prod)", "Edit(**/.env.prod)",
      "Read(./.env.prod.local)", "Edit(./.env.prod.local)",
      "Read(**/.env.prod.local)", "Edit(**/.env.prod.local)",
      "Read(./.env.staging)", "Edit(./.env.staging)",
      "Read(**/.env.staging)", "Edit(**/.env.staging)",
      "Read(./.env.staging.local)", "Edit(./.env.staging.local)",
      "Read(**/.env.staging.local)", "Edit(**/.env.staging.local)",
      "Read(./.env.stage)", "Edit(./.env.stage)",
      "Read(**/.env.stage)", "Edit(**/.env.stage)",
      "Read(./.env.stage.local)", "Edit(./.env.stage.local)",
      "Read(**/.env.stage.local)", "Edit(**/.env.stage.local)",
      "Read(./.env.test)", "Edit(./.env.test)",
      "Read(**/.env.test)", "Edit(**/.env.test)",
      "Read(./.env.test.local)", "Edit(./.env.test.local)",
      "Read(**/.env.test.local)", "Edit(**/.env.test.local)",
      "Read(./.env.testing)", "Edit(./.env.testing)",
      "Read(**/.env.testing)", "Edit(**/.env.testing)",
      "Read(./.env.ci)", "Edit(./.env.ci)",
      "Read(**/.env.ci)", "Edit(**/.env.ci)",
      "Read(./.env.docker)", "Edit(./.env.docker)",
      "Read(**/.env.docker)", "Edit(**/.env.docker)",
      "Read(./.env.preview)", "Edit(./.env.preview)",
      "Read(**/.env.preview)", "Edit(**/.env.preview)",
      "Read(./.env.qa)", "Edit(./.env.qa)",
      "Read(**/.env.qa)", "Edit(**/.env.qa)",
      "Read(./.env.uat)", "Edit(./.env.uat)",
      "Read(**/.env.uat)", "Edit(**/.env.uat)",
      "Read(./.envrc)", "Edit(./.envrc)",
      "Read(**/.envrc)", "Edit(**/.envrc)",
      "Read(**/id_rsa)", "Edit(**/id_rsa)",
      "Read(**/id_ed25519)", "Edit(**/id_ed25519)",
      "Read(**/id_dsa)", "Edit(**/id_dsa)",
      "Read(**/id_ecdsa)", "Edit(**/id_ecdsa)",
      "Read(**/*.ppk)", "Edit(**/*.ppk)",
      "Read(**/*.pem)", "Edit(**/*.pem)",
      "Read(**/*.key)", "Edit(**/*.key)",
      "Read(**/*.pfx)", "Edit(**/*.pfx)",
      "Read(**/*.p12)", "Edit(**/*.p12)",
      "Read(**/*.jks)", "Edit(**/*.jks)",
      "Read(**/*.keystore)", "Edit(**/*.keystore)",
      "Read(./.aws/credentials)", "Edit(./.aws/credentials)",
      "Read(**/.aws/credentials)", "Edit(**/.aws/credentials)",
      "Read(./application_default_credentials.json)", "Edit(./application_default_credentials.json)",
      "Read(**/application_default_credentials.json)", "Edit(**/application_default_credentials.json)",
      "Read(**/legacy_credentials/**)", "Edit(**/legacy_credentials/**)",
      "Read(./.azure/accessTokens.json)", "Edit(./.azure/accessTokens.json)",
      "Read(**/.azure/accessTokens.json)", "Edit(**/.azure/accessTokens.json)",
      "Read(./.azure/azureProfile.json)", "Edit(./.azure/azureProfile.json)",
      "Read(**/.azure/azureProfile.json)", "Edit(**/.azure/azureProfile.json)",
      "Read(./.docker/config.json)", "Edit(./.docker/config.json)",
      "Read(**/.docker/config.json)", "Edit(**/.docker/config.json)",
      "Read(./.kube/config)", "Edit(./.kube/config)",
      "Read(**/.kube/config)", "Edit(**/.kube/config)",
      "Read(./.netrc)", "Edit(./.netrc)",
      "Read(**/.netrc)", "Edit(**/.netrc)",
      "Read(./.git-credentials)", "Edit(./.git-credentials)",
      "Read(**/.git-credentials)", "Edit(**/.git-credentials)",
      "Read(./.npmrc)", "Edit(./.npmrc)",
      "Read(**/.npmrc)", "Edit(**/.npmrc)",
      "Read(./.pypirc)", "Edit(./.pypirc)",
      "Read(**/.pypirc)", "Edit(**/.pypirc)",
      "Read(./.yarnrc.yml)", "Edit(./.yarnrc.yml)",
      "Read(**/.yarnrc.yml)", "Edit(**/.yarnrc.yml)",
      "Read(./.cargo/credentials.toml)", "Edit(./.cargo/credentials.toml)",
      "Read(**/.cargo/credentials.toml)", "Edit(**/.cargo/credentials.toml)",
      "Read(./.gem/credentials)", "Edit(./.gem/credentials)",
      "Read(**/.gem/credentials)", "Edit(**/.gem/credentials)",
      "Read(**/*.tfstate*)", "Edit(**/*.tfstate*)",
      "Read(./*.tfvars)", "Edit(./*.tfvars)",
      "Read(**/*.tfvars)", "Edit(**/*.tfvars)",
      "Read(**/*.tfvars.json)", "Edit(**/*.tfvars.json)",
      "Read(./.terraformrc)", "Edit(./.terraformrc)",
      "Read(**/.terraformrc)", "Edit(**/.terraformrc)",
      "Read(./.terraform.d/credentials.tfrc.json)", "Edit(./.terraform.d/credentials.tfrc.json)",
      "Read(**/.terraform.d/credentials.tfrc.json)", "Edit(**/.terraform.d/credentials.tfrc.json)",
      "Read(./secrets.yaml)", "Edit(./secrets.yaml)",
      "Read(**/secrets.yaml)", "Edit(**/secrets.yaml)",
      "Read(./secrets.yml)", "Edit(./secrets.yml)",
      "Read(**/secrets.yml)", "Edit(**/secrets.yml)",
      "Read(./credentials.json)", "Edit(./credentials.json)",
      "Read(**/credentials.json)", "Edit(**/credentials.json)",
      "Read(./config/master.key)", "Edit(./config/master.key)",
      "Read(**/config/master.key)", "Edit(**/config/master.key)",
      "Read(./config/credentials.yml.enc)", "Edit(./config/credentials.yml.enc)",
      "Read(**/config/credentials.yml.enc)", "Edit(**/config/credentials.yml.enc)",
      "Read(./wp-config.php)", "Edit(./wp-config.php)",
      "Read(**/wp-config.php)", "Edit(**/wp-config.php)",
      "Read(./local_settings.py)", "Edit(./local_settings.py)",
      "Read(**/local_settings.py)", "Edit(**/local_settings.py)",
      "Read(./settings_local.py)", "Edit(./settings_local.py)",
      "Read(**/settings_local.py)", "Edit(**/settings_local.py)",
      "Read(./.bash_history)", "Edit(./.bash_history)",
      "Read(**/.bash_history)", "Edit(**/.bash_history)",
      "Read(./.zsh_history)", "Edit(./.zsh_history)",
      "Read(**/.zsh_history)", "Edit(**/.zsh_history)",
      "Read(./.psql_history)", "Edit(./.psql_history)",
      "Read(**/.psql_history)", "Edit(**/.psql_history)",
      "Read(./.mysql_history)", "Edit(./.mysql_history)",
      "Read(**/.mysql_history)", "Edit(**/.mysql_history)",
      "Read(./.python_history)", "Edit(./.python_history)",
      "Read(**/.python_history)", "Edit(**/.python_history)",
      "Bash(*.env*)",
      "Bash(*id_rsa*)",
      "Bash(*id_ed25519*)",
      "Bash(*id_dsa*)",
      "Bash(*id_ecdsa*)",
      "Bash(*.ppk*)",
      "Bash(*.pem*)",
      "Bash(*.key*)",
      "Bash(*.pfx*)",
      "Bash(*.p12*)",
      "Bash(*.jks*)",
      "Bash(*.keystore*)",
      "Bash(*.aws/credentials*)",
      "Bash(*application_default_credentials.json*)",
      "Bash(*legacy_credentials*)",
      "Bash(*.azure/accessTokens.json*)",
      "Bash(*.azure/azureProfile.json*)",
      "Bash(*.docker/config.json*)",
      "Bash(*.kube/config*)",
      "Bash(*.netrc*)",
      "Bash(*.git-credentials*)",
      "Bash(*.npmrc*)",
      "Bash(*.pypirc*)",
      "Bash(*.yarnrc.yml*)",
      "Bash(*.cargo/credentials.toml*)",
      "Bash(*.gem/credentials*)",
      "Bash(*.tfstate*)",
      "Bash(*.tfvars*)",
      "Bash(*.terraformrc*)",
      "Bash(*.terraform.d/credentials.tfrc.json*)",
      "Bash(*secrets.yaml*)",
      "Bash(*secrets.yml*)",
      "Bash(*credentials.json*)",
      "Bash(*config/master.key*)",
      "Bash(*config/credentials.yml.enc*)",
      "Bash(*wp-config.php*)",
      "Bash(*local_settings.py*)",
      "Bash(*settings_local.py*)",
      "Bash(*.bash_history*)",
      "Bash(*.zsh_history*)",
      "Bash(*.psql_history*)",
      "Bash(*.mysql_history*)",
      "Bash(*.python_history*)",
      "Bash(rm -rf *)",
      "Bash(sudo rm *)",
      "Bash(git push --force*)",
      "Bash(git reset --hard*)",
      "Bash(git clean -f*)",
      "Bash(chmod -R 777 *)"
    ]
  },
  "defaultMode": "plan",
  "includeCoAuthoredBy": false
}
