{
  "mcpServers": {
    "neal-todos": {
      "type": "http",
      "url": "http://kewtie:3737/mcp/__TODO_MCP_TOKEN__"
    }
  },
  "permissions": {
    "allow": [
      "mcp__claude_ai_neal_todo__*",
      "WebSearch",
      "WebFetch",
      "Read",
      "Edit",
      "Write",
      "Bash(npm *)",
      "Bash(pnpm *)",
      "Bash(node *)",
      "Bash(uv *)",
      "Bash(brew list*)",
      "Bash(brew info*)",
      "Bash(brew search*)",
      "Bash(docker ps*)",
      "Bash(docker logs*)",
      "Bash(docker exec*)",
      "Bash(docker inspect*)",
      "Bash(docker build*)",
      "Bash(docker images*)",
      "Bash(docker history*)",
      "Bash(docker restart*)",
      "Bash(docker compose ps*)",
      "Bash(docker compose logs*)",
      "Bash(docker compose build*)",
      "Bash(docker compose restart*)",
      "Bash(docker compose up*)",
      "Bash(podman ps*)",
      "Bash(podman logs*)",
      "Bash(podman exec*)",
      "Bash(podman inspect*)",
      "Bash(podman build*)",
      "Bash(podman images*)",
      "Bash(podman history*)",
      "Bash(podman restart*)",
      "Bash(podman compose ps*)",
      "Bash(podman compose logs*)",
      "Bash(podman compose build*)",
      "Bash(podman compose restart*)",
      "Bash(podman compose up*)",
      "Bash(sqlite3 -readonly *)",
      "Bash(ls*)",
      "Bash(find *)",
      "Bash(grep *)",
      "Bash(cat *)",
      "Bash(echo *)",
      "Bash(pwd)",
      "Bash(which *)",
      "Bash(env)",
      "Bash(printenv *)",
      "Bash(curl *)",
      "Bash(python3 *)",
      "Bash(jq *)"
    ],
    "deny": [
      "Read(./.env)", "Edit(./.env)", "Write(./.env)",
      "Read(./.env.*)", "Edit(./.env.*)", "Write(./.env.*)",
      "Read(**/.env)", "Edit(**/.env)", "Write(**/.env)",
      "Read(**/.env.*)", "Edit(**/.env.*)", "Write(**/.env.*)",
      "Read(./.envrc)", "Edit(./.envrc)", "Write(./.envrc)",
      "Read(**/.envrc)", "Edit(**/.envrc)", "Write(**/.envrc)",
      "Read(**/id_rsa)", "Edit(**/id_rsa)", "Write(**/id_rsa)",
      "Read(**/id_ed25519)", "Edit(**/id_ed25519)", "Write(**/id_ed25519)",
      "Read(**/*.pem)", "Edit(**/*.pem)", "Write(**/*.pem)",
      "Read(**/*.key)", "Edit(**/*.key)", "Write(**/*.key)",
      "Read(./.aws/credentials)", "Edit(./.aws/credentials)", "Write(./.aws/credentials)",
      "Read(**/.aws/credentials)", "Edit(**/.aws/credentials)", "Write(**/.aws/credentials)",
      "Read(./.docker/config.json)", "Edit(./.docker/config.json)", "Write(./.docker/config.json)",
      "Read(**/.docker/config.json)", "Edit(**/.docker/config.json)", "Write(**/.docker/config.json)",
      "Read(./.kube/config)", "Edit(./.kube/config)", "Write(./.kube/config)",
      "Read(**/.kube/config)", "Edit(**/.kube/config)", "Write(**/.kube/config)",
      "Read(./.netrc)", "Edit(./.netrc)", "Write(./.netrc)",
      "Read(**/.netrc)", "Edit(**/.netrc)", "Write(**/.netrc)",
      "Read(./.git-credentials)", "Edit(./.git-credentials)", "Write(./.git-credentials)",
      "Read(**/.git-credentials)", "Edit(**/.git-credentials)", "Write(**/.git-credentials)",
      "Read(./.npmrc)", "Edit(./.npmrc)", "Write(./.npmrc)",
      "Read(**/.npmrc)", "Edit(**/.npmrc)", "Write(**/.npmrc)",
      "Read(./.pypirc)", "Edit(./.pypirc)", "Write(./.pypirc)",
      "Read(**/.pypirc)", "Edit(**/.pypirc)", "Write(**/.pypirc)",
      "Read(**/*.tfstate*)", "Edit(**/*.tfstate*)", "Write(**/*.tfstate*)",
      "Read(./secrets.yaml)", "Edit(./secrets.yaml)", "Write(./secrets.yaml)",
      "Read(**/secrets.yaml)", "Edit(**/secrets.yaml)", "Write(**/secrets.yaml)",
      "Read(./secrets.yml)", "Edit(./secrets.yml)", "Write(./secrets.yml)",
      "Read(**/secrets.yml)", "Edit(**/secrets.yml)", "Write(**/secrets.yml)",
      "Read(./credentials.json)", "Edit(./credentials.json)", "Write(./credentials.json)",
      "Read(**/credentials.json)", "Edit(**/credentials.json)", "Write(**/credentials.json)",
      "Bash(*.env*)",
      "Bash(*id_rsa*)",
      "Bash(*id_ed25519*)",
      "Bash(*.pem*)",
      "Bash(*.key*)",
      "Bash(*.aws/credentials*)",
      "Bash(*.docker/config.json*)",
      "Bash(*.kube/config*)",
      "Bash(*.netrc*)",
      "Bash(*.git-credentials*)",
      "Bash(*.npmrc*)",
      "Bash(*.pypirc*)",
      "Bash(*.tfstate*)",
      "Bash(*secrets.yaml*)",
      "Bash(*secrets.yml*)",
      "Bash(*credentials.json*)",
      "Bash(rm -rf *)",
      "Bash(sudo rm *)",
      "Bash(git push --force*)",
      "Bash(git reset --hard*)",
      "Bash(git clean -f*)",
      "Bash(chmod -R 777 *)"
    ]
  },
  "defaultMode": "plan",
  "includeCoAuthoredBy": false
}
