#!/usr/bin/env bash
# gen_ssh_config.sh — writes ~/.ssh/config from .machines.json + ssh_config.base
# Run via: genssh

_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_is_darwin=0
[ "$(uname -s)" = "Darwin" ] && _is_darwin=1

python3 - "$_dir/.machines.json" "$_dir/ssh_config.base" "$_is_darwin" <<'PY'
import json, sys, os, pathlib

json_path, base_path, is_darwin = sys.argv[1], sys.argv[2], sys.argv[3] == "1"

with open(json_path) as f:
    hosts = json.load(f)["hosts"]

lines = [
    "# ~/.ssh/config — generated by gen_ssh_config.sh",
    "# Edit ~/repos/dotfiles/.machines.json or ssh_config.base, then run: genssh",
    "# Do not edit this file directly.",
    "",
]

for h in hosts:
    name    = h["name"]
    user    = h["user"]
    ip      = h.get("local_ip")
    ts_host = h.get("tailscale_hostname", name)
    env     = h.get("ssh_set_env", {})
    env_lines = [f"    SetEnv {k}={v}" for k, v in env.items()]

    lines.append(f"# {name} — tailnet")
    lines.append(f"Host {name}-tailnet")
    lines.append(f"    HostName {ts_host}")
    lines.append(f"    User {user}")
    lines.extend(env_lines)
    lines.append("")

    if ip:
        lines.append(f"# {name} — lan")
        lines.append(f"Host {name}-lan")
        lines.append(f"    HostName {ip}")
        lines.append(f"    User {user}")
        lines.extend(env_lines)
        lines.append("")

if os.path.isfile(base_path):
    with open(base_path) as f:
        base_lines = f.read().rstrip("\n").split("\n")
    if not is_darwin:
        # UseKeychain is a macOS-only OpenSSH keyword; portable OpenSSH on
        # Linux fatals on it ("Bad configuration option"), so strip the
        # directive lines (not comments) rather than rely on IgnoreUnknown
        # scoping to save it.
        def is_usekeychain_directive(l):
            keyword = l.strip().split(None, 1)[0].lower() if l.strip() and not l.strip().startswith("#") else ""
            return keyword in ("usekeychain", "ignoreunknown")
        base_lines = [l for l in base_lines if not is_usekeychain_directive(l)]
    lines.append("\n".join(base_lines).rstrip())
    lines.append("")

out = pathlib.Path.home() / ".ssh" / "config"
out.parent.mkdir(mode=0o700, exist_ok=True)
out.write_text("\n".join(lines) + "\n")
print(f"wrote ~/.ssh/config ({len(hosts)} hosts)")
PY
